### ISSUE TITLE
Rethink :series_name_for_x configuration

### ISSUE THREAD

**Issue by dmke** [InfluxCommunity/influxdb-rails#56]
I'm contemplating to reduce the number of config options for the series this gem writes creates:

https://github.com/influxdata/influxdb-rails/blob/cbfd10b6a9611ae52b202896c98b6ff29e3d0a29/lib/influxdb/rails/configuration.rb#L19-L23

with these default values:

https://github.com/influxdata/influxdb-rails/blob/cbfd10b6a9611ae52b202896c98b6ff29e3d0a29/lib/influxdb/rails/configuration.rb#L63-L67

## Reasons

1. The nomenclature is misleading, it stems from some time ago, when "series name" was the right vocabulary. These attributes actually mean "measurement name". A "series" in InfluxDB 0.9+ means values for a given measurement.
2. Aggregating across multiple measurements is hard (if not impossible). The current setup needs to send five queries to InfluxDB to get the full picture. The PR #53 adds three more, and #55 will add another.

## Proposed change

Let there be only one measurement configurable, say `Configuration#measurement_name` with default value "rails". What was previously written to different measurements, should now get an additional tag to differentiate the source.

Exemplary change for `InfluxDB::Rails::Instrumentation`:

```diff
@@ def benchmark_for_instrumentation @@
 InfluxDB::Rails.client.write_point \
-  c.series_name_for_instrumentation,
+  c.measurement_name,
   values: {
     value: ((Time.now - start) * 1000).ceil,
   },
   tags:   configuration.tags_middleware.call(
+    series: "instrumentation",
     method: "#{controller_name}##{action_name}",
     server: Socket.gethostname
   )
```

*N.B.* Not having a dot in the measurement name also makes writing the queries easier, as it does not need to be escaped, because the from clause may have three incarnations:

1. `FROM <database_name>.<retention_policy_name>.<measurement_name>` – full qualified
2. `FROM <database_name>..<measurement_name>` – using default retention policy
3. `FROM <measurement_name>` – using current database and default retention policy

without paying attention, this does raise an error ("retention policy not found"):

```sql
select * from rails.db
```

By eliminating the dot in the name, it becomes easier:

```sql
select * from "rails.db" where ...            -- before: needs escaping
select * from rails where series = 'db' ...   -- after: less escaping
```

## Impact on existing users

Existing data could be migrated, and we should support users in doing so. I've already written a [short script](https://gist.github.com/dmke/2d0f4ccf9f43faf82e732dc041e90ca2) to migrate the exception measurement (#43), which could be used as a guide.

Existing tooling will break, but changes should be straightforward. For Grafana users, we could create an "official" dashboard to ease the transition. This is a stretch goal though, so it should go into a separate issue.

## Tasks

- [x] modify README.md
- [x] change `InfluxDB::Rails::Configuration`
- [ ] update subscriber classes
- [ ] create upgrade guide for pre-1.0 users

**Comment by ChrisBr** [comment]
>  For Grafana users, we could create an "official" dashboard to ease the transition. This is a stretch goal though, so it should go into a separate issue.

This would be a HUGE benefit. We still struggle to build a meaningful dashboard :cry: Our public openSUSE Grafana dashboard is located here if you want to have a look:

https://metrics.opensuse.org/d/qjkd7uBmz/rails-metrics?orgId=1&from=now%2Fd&to=now%2Fd

I would volunteer to helper here but definitely need some guidance as I'm still new to InfluxDB and Grafana unfortunately.

**Comment by ChrisBr** [comment]
I would also like to refactor the ``SimpleSubscriber`` to be useful out of the box and users can just subscribe to any ActiveSupport hook like this:

```
series_name = 'series_name'
tags = [:foo, :bar]
normalizer = Proc.new { }
subscriber = InfluxDB::Rails::Subscriber.new('series_name'
ActiveSupport::Notifications.subscribe('the_notification', tags, normalizer)
```

The tags would be an array of the tags which should be extracted from the notification data. The normalizer is a proc which gets called with the data and optinally transforms it.

Not sure yet how the data will be structured in the influxdb though. What do you think?

**Comment by dmke** [comment]
> users can just subscribe to any ActiveSupport hook

That's a useful addition.

> Not sure yet how the data will be structured in the influxdb though.

At its core, it's "just" a key-value store. Some keys are special, in that their associated values con only be strings, but are indexed (tags), one key is used for absolute ordering (time), and the other keys may hold arbitrary values (fields).

The challenge, if we open that for general use, is to communicate the distinction between tags and fields. Tags should, generally speaking, only hold data with low cardinality (i.e. the distinct set of values small). You've seen in #50/#54 that unbound values can cause problems. Subscriber implementators should be made aware of this, at least with an API that is hard to misuse.

**Comment by ChrisBr** [comment]
>  Subscriber implementators should be made aware of this, at least with an API that is hard to misuse.

Yep, right. What about adding a blacklist of keys from Active Support instrumentation and write an error message to the logs? The user could still misuse it but at least they get an notification. The blacklist would e.g. contain ``[:identifier, :id, :key, :to, :from, :cc, :bcc, :date ...]``. I don't think that the black list would be extensive. Maybe we could even be more restrictive and just don't send those tags to InfluxDB and write in the documentation that we remove these tags because of their cardinality.

**Comment by dmke** [comment]
> write an error message to the logs? [...] Maybe we could even be more restrictive and just don't send those tags to InfluxDB and write in the documentation that we remove these tags because of their cardinality.

Unless it's an exception, I doubt most users will ever look into the `production.log` (then again, the typical use case for this gem isn't the 15-minute blog app). Also, silently dropping the data points would not be what the user expects. If they normalize some value, they'll wonder why that value doesn't show up in the server measurement, only to discover after hours of debugging, that the key is blacklisted for some reason.

> What about adding a blacklist of keys

That might work, but it creates a maintenance burden: whenever the payload keys are changed upstream, we propably need to modify this gem as well (I don't have the resources (i.e. time) to do that).

I was more thinking of something like

```ruby
InfluxDB::Rails.subscribe(
  series:         "series_name",
  notification:   "the_notification"
  payload_tags:   %i[t1 t2 t3],
  payload_fields: %i[f1 f2]
) do |tags, fields|
  # optional normalizing
end
```

and have a bit of documentation explaining the `payload_*` keys.

**Comment by dmke** [comment]
~~Btw. let me move this conversation to another issue.~~ → #60

**Comment by ChrisBr** [comment]
Hey @dmke any update regarding this one or anything I could help out? Looked at your branch and it looks good so far so just wondering...

**Comment by dmke** [comment]
Here's where I left the `refactor/measurements` branch:

1. I've updated the README to reflect the targeted changes (documentation driven design :-)).
2. I've refactored the configuration. This is mostly DRY'up, but I also already removed the `:series_name_for_*` keys, and introduced `:report_*` keys.
3. I've started to tackle failing specs, but there's [still a lot to do](https://travis-ci.org/influxdata/influxdb-rails/jobs/474142352).

In the past weeks, I've sadly not found a few consecutive hours to continue on this. If you wanna get dirty and take a stab at this, feel free to do so. Any help is greatly appreciated :-)

**Comment by ChrisBr** [comment]
>  If you wanna get dirty and take a stab at this, feel free to do so. Any help is greatly appreciated :-)

Ok, so do I get it right that there are basically only fixing the failing specs left?

**Comment by ChrisBr** [comment]
I know you're busy but could we get https://github.com/influxdata/influxdb-rails/pull/65 & https://github.com/influxdata/influxdb-rails/pull/64 merged before I continue with this one? Otherwise I fear we probably get quite some merge conflicts....

**Comment by dmke** [comment]
> Ok, so do I get it right that there are basically only fixing the failing specs left?

That and a guide describing how existing users can migrate pre-1.0 data. Maybe add a piece of code that does this.

> could we get #65 & #64 merged 

Sure, I'll do so when I'm back home.

**Comment by dmke** [comment]
I've merged the PRs and rebased the refactoring branch onto master.

**Comment by hennevogel** [comment]
Fixed in #66
